### ISSUE TITLE
Line Segment Dataset / Format

### ISSUE THREAD

**Issue by ty-fel** [hanlinm2/projective-geometry#1]
Hi, thank you for sharing your work!

I was wondering if the lines dataset could be shared, I only see all_outdoor_problem_paths.pkl on the google drive link. This pkl seems to just contain image filepaths.

Related, I was curious about the format for the lines data. Specifically how the output from DeepLSD was formatted to be loaded into the ClassificationPointNet. It seems that the out["lines"][0] output from the DeepLSD needs to be reshaped from (# lines, 2, 2) to (# lines, 4) but was was wondering if that is correct.

**Comment by hanlinm2** [comment]
Hi. Thank you for pointing it out. Looks like we were missing a file that failed to be uploaded. `image_path_to_lines.pkl` is now uploaded. Please check again. 

`line_segment/lines_path_helpers.py` describes how to load the dataset, but it's basically the following:
```
>>> import pickle
>>> load_path = "dataset/image_path_to_lines.pkl"
>>> with open(load_path, 'rb') as f:
...     image_path_to_lines = pickle.load(f)
>>> list(image_path_to_lines.keys())[0]
'../dataset/Kandinsky_Indoor/train/real/1.jpg'
>>> list(image_path_to_lines.values())[0].shape
(62, 4)
>>> list(image_path_to_lines.values())[1].shape
(112, 4)
```

And yes your description for the formatting is correct.

Hope this answers your question.
