### ISSUE TITLE
How do you determine the vanishing points? And how do you draw the intersecting lines?

### ISSUE THREAD

**Issue by Roger-JiahaoZhang** [hanlinm2/projective-geometry#2]
I couldn't find any information about vanishing points in either the article or the code.

**Comment by hanlinm2** [comment]
Hi. We don't directly generate vanishing points. We use DeepLSD to detect line segments and then train a network based on PointNet architecture to distinguish between real and generated images. The intersecting lines in the teaser are drawn by hand to illustrate the errors that exist in generated images that can be detected by the PointNet. 

<img width="586" alt="Screenshot 2024-09-14 at 8 24 39 PM" src="https://github.com/user-attachments/assets/21be1a0b-5a78-4407-8ff5-d6affbe0cdc6">

**Comment by Roger-JiahaoZhang** [comment]
Thank you so much, this completely resolved my question.
